name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        export PYTHONPATH="$PWD"
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd backend
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
        # exit-zero treats all errors as warnings.
        flake8 . --exit-zero --max-complexity=10
    - name: Test with pytest
      run: |
        cd backend
        python3 -m pytest
